version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
c89d92a1bee2049ddf4f825e39fb4c256b9a8814
vuit469866trghui8876tdghjiigfee5689ohgf45https://github.com/Avalir1996/187Strassenbande.git